### ISSUE TITLE
Store classic mode deprecated

### ISSUE THREAD

**Issue by smnscp** [vuex-orm/vuex-orm-examples-nuxt#1]
Since the Vuex store is configured in [classic mode](https://nuxtjs.org/guide/vuex-store#classic-mode) we get a warning in the console saying “Classic mode for store/ is deprecated and will be removed in Nuxt 3.”
We should adjust store/index.js to use modules mode and [export plugins](https://nuxtjs.org/guide/vuex-store#plugins).

**Comment by ml-haivx** [comment]
I'm also having trouble implementing Vue-orm with Modules mode. Would you be able to provide a sample?

**Comment by smnscp** [comment]
Hi @ml-haivx, please take a look at my pull request #2. You can just apply these changes in your project and it should work.

**Comment by kiaking** [comment]
Sorry it took so long but the issue is resolved by #2! Thanks to @smnscp 👍
