### ISSUE TITLE
[Feature Suggestion] Add CRUD and Async fetch feeds

### ISSUE THREAD

**Issue by connecteev** [vuex-orm/vuex-orm-examples-nuxt#3]
Thanks for the really nice code example in Nuxt and Vuex. I'm still very new to Nuxt.js, but I'm learning slowly.

Can we add a CRUD example and async/ fetch example for a json feed, that makes use of your [vuex-orm package](https://github.com/vuex-orm/vuex-orm)?

Here are some links from my investigation:

1. https://github.com/nuxt/hackernews (this is a 1st party package from the creators of Nuxt. As elegant as it is, it's not simple for me to grasp everything. This doesn't have CRUD but is a really nice example of fetching json feeds, caching of feeds, etc.) Demo at https://hn.nuxtjs.org/

2. https://github.com/nico-amsterdam/vue-crud-nuxt (demo link [here](https://codepen.io/shershen08/pen/xROOxw)). This is a great example of CRUD in Nuxt.

3. https://github.com/guillaumebriday/todolist-frontend-nuxt
Another great example of CRUD in Nuxt (it uses your vuex-orm package)

Can we add CRUD and async fetch for feeds (like in the [hackernews repo](https://github.com/nuxt/hackernews)) to this repo?

**Comment by kiaking** [comment]
@connecteev Hi! Thank you so much for the feedback!

Very nice idea! Let's do this. I want to keep one repo as simple as possible since Vuex ORM requires more code compared to others. So I'm thinking to have another repository something like `vuex-orm-examples-nuxt-hackernews`.

**Comment by connecteev** [comment]
@kiaking great! I think the hackernews clone has been done a few times. 

Can we do a nice CRUD example (it's also more widely applicable) and replicate https://codepen.io/shershen08/pen/xROOxw using https://github.com/nico-amsterdam/vue-crud-nuxt ? A lot of that code exists already, just have to translate it to vuex-orm.
I can help with the backend, if you like....I'll most likely do it in laravel.
I like the concept of vuex-orm and will definitely use it if this CRUD example can be done.

**Comment by kiaking** [comment]
@connecteev I think we could? But I guess to make the example simple I think it's better to use existing external API instead of making our own backend. What do you think?

**Comment by connecteev** [comment]
@kiaking great. If you do the frontend (since i'm just learning nuxt / vue and you seem to know more on this), I will do the backend for the CRUD, it will be in Laravel. It can be an accompanying repo to this one and live under vuex-orm/laravel-apis --- let me know what you think and I'll be done in 2-3 days. This will help my project and also others that use this end to end vuex-orm+ajax example. I'll also write a readme for installation, so anyone can get up and running in a few min. Thoughts?

We can pick maybe a few DB tables / models. Example:
```
posts (post hasandbelongstomany tags)
tags (tag hasandbelongstomany posts)
post_tags 
```
I'll still need to think about and come up with some sort of balsamiq wireframes for you. I'll need to plan out my time over the next few days (right now it looks like i can squeeze this in before wed) so let me know if this is of interest and what your schedule looks like.

**Comment by kiaking** [comment]
Nice! In that case, we could make an example `vuex-orm-examples-laravel` to show that it is a real app example.

**Comment by connecteev** [comment]
That works. I'll start working on it if you want to create the project and invite me in. When do you expect to start with the front-end, and how do you want to collab on wireframes and other ideas?

**Comment by kiaking** [comment]
I'll create a repo and create an issue in that! We can then discuss about UI design, functionality and folder structure and such.

**Comment by connecteev** [comment]
great!

**Comment by kiaking** [comment]
@connecteev I've created the repo!
https://github.com/vuex-orm/vuex-orm-examples-laravel

Could you organize the issues to move things forward? Like what task will be needed and such. Once those issues are created, let's close this issue and move over there to continue discussion.

**Comment by connecteev** [comment]
@kiaking You need to add me as an admin to that repo, otherwise I can't check any code in. I'll also log issues in there once that's done, we can discuss after both those things are done.

**Comment by kiaking** [comment]
@connecteev There is no code yet. I haven't pushed anything. To add code, we must decide what code to add at first place (how should directory looks like and such). Does this make sense?

**Comment by connecteev** [comment]
@kiaking okay, will log some issues in there first...take a look and let me know

**Comment by kiaking** [comment]
We've created a new repo and started discussing at https://github.com/vuex-orm/vuex-orm-examples-laravel/issues/1. I'll close this issue. Let's create some cool stuff! 👍
