### ISSUE TITLE
Igor

### ISSUE THREAD

**Issue by igorpopryadukhin** [vuex-orm/vuex-orm-examples-nuxt#4]
// Here we are stubbing the initial data. In the real world, this
`
async fetch () {
    // Here we are stubbing the initial data. In the real world, this
    // should be the response from the API Backend.
    const initialData = await data()
    Todo.create({ data: initialData })
  }
`

**Comment by kiaking** [comment]
@igorpopryadukhin Hi! thank you for opening the issue! Not quite sure what is your intention is. Could you elaborate a bit more?

**Comment by igorpopryadukhin** [comment]
https://github.com/vuex-orm/vuex-orm-examples-nuxt/blob/master/pages/index.vue
Line 35
Are we downloading data or drowning out?

Sorry, I don't speak English at all

**Comment by kiaking** [comment]
@igorpopryadukhin It's downloading data! Other words, it's importing external data into Vuex ORM.

**Comment by kiaking** [comment]
@igorpopryadukhin Do you have any additional questions? Is it OK if I close this issue?

**Comment by cuebit** [comment]
Closing the issue due to inactivity. Please feel free to open another issue if there's anything! 🤝
